Api business logic feature
d-kv/signer pull request #37
Opened 2024-04-26 18:18 UTC by themotka

without realisation of status commands and queries

2024-04-29 21:02 UTC, maksmolchdmitr requested changes

2024-04-29 21:02 UTC, maksmolchdmitr commented on db-common/entity/commands.go
> +var ValidPlatforms = []string{"IOS", "MAC_OS"}
rename to PlatformValues

2024-04-29 21:02 UTC, maksmolchdmitr commented on db-common/entity/commands.go
> +var ValidCapabilities = []string{"IN_APP_PURCHASE", "PUSH_NOTIFICATIONS", "APPLE_PAY", "NFC_TAG_READING", "APPLE_ID_AUTH"}
rename to CapabilitiesTypeValues

2024-04-29 21:02 UTC, maksmolchdmitr commented on db-common/entity/commands.go
> +var ValidStatuses = []string{"CREATED", "PROCESSING", "COMPLETED", "ERROR"}
rename to StatusValues

2024-04-30 07:01 UTC, themotka commented on api/internal/client-service/command-executor.go
> +	panic("implement me")
друг, это дефолтное заполнение нереализованных методов интерфейса

2024-05-01 08:37 UTC, themotka commented on db-common/entity/commands.go
> +var ValidCapabilities = []string{"IN_APP_PURCHASE", "PUSH_NOTIFICATIONS", "APPLE_PAY", "NFC_TAG_READING", "APPLE_ID_AUTH"}
renamed -> CapabilityTypeValues

2024-05-01 08:37 UTC, themotka commented on db-common/entity/commands.go
> +var ValidPlatforms = []string{"IOS", "MAC_OS"}
renamed

2024-05-01 12:30 UTC, maksmolchdmitr commented on api/internal/client-service/command-executor.go
> +	panic("implement me")
хаха, такое дефолтное что даже сервис тупо упадет

2024-05-01 12:30 UTC, maksmolchdmitr commented on api/internal/client-service/command-executor.go
> +	panic("implement me")
ну ладно пофиг

2024-05-01 12:31 UTC, maksmolchdmitr approved these changes

2024-05-01 12:32 UTC, merged