refactored successfully
d-kv/signer pull request #38
Opened 2024-04-27 18:19 UTC by themotka

ready

2024-04-29 20:26 UTC, maksmolchdmitr requested changes

2024-04-29 20:26 UTC, maksmolchdmitr commented on query-handler/pkg/httpserver/handlers/router.go
> +		//}
Не виже смысла в том чтобы комментировать код, если он не нужен и пригодится в будущем, то можно просто оставить этот код без комментирования!

2024-04-30 07:05 UTC, themotka commented on query-handler/pkg/httpserver/handlers/router.go
> +		//}
я вижу смысл

2024-04-30 07:05 UTC, merged

2024-05-01 12:32 UTC, maksmolchdmitr commented on query-handler/pkg/httpserver/handlers/router.go
> +		//}
окей